/**
 * @file osTaskManager.h
 * @brief C-linkage declaration of the supercycle driver.
 *
 * Implemented in tasks/osTaskManager.cpp. Declared here with C
 * linkage so a plain C main.c (as generated by vendor tools like
 * STM32CubeIDE) can call it without including any C++ headers.
 *
 * @author uSliceCore Team
 */

#pragma once

#ifdef __cplusplus
extern "C" {
#endif

/**
 * @brief Runs the supercycle forever. Never returns.
 * Call once from main(), after all tasks are registered.
 */
void osTaskManager(void);

#ifdef __cplusplus
}
#endif
